[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "morse_translator"
version = "0.0.1"

[project.scripts]
morse_translator = "morse_translator_cli:main"

[tool.setuptools]
py-modules = ["morse_translator_cli"]
packages = ["morse_translator"]
